export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const GET_CLASS_FAILURE = "GET_CLASS_FAILURE";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const GET_ASSIGNMENT_REQUEST = "GET_ASSIGNMENT_REQUEST";
export const GET_ASSIGNMENT_SUCCESS = "GET_ASSIGNMENT_SUCCESS";
export const GET_ASSIGNMENT_FAILURE = "GET_ASSIGNMENT_FAILURE";

export const GET_SUBMISSION_REQUEST = "GET_SUBMISSION_REQUEST";
export const GET_SUBMISSION_SUCCESS = "GET_SUBMISSION_SUCCESS";
export const GET_SUBMISSION_FAILURE = "GET_SUBMISSION_FAILURE";

export const GET_ASSIGNMENT_SUBMISSION_REQUEST = "GET_ASSIGNMENT_SUBMISSION_REQUEST";
export const GET_ASSIGNMENT_SUBMISSION_SUCCESS = "GET_ASSIGNMENT_SUBMISSION_SUCCESS";
export const GET_ASSIGNMENT_SUBMISSION_FAILURE = "GET_ASSIGNMENT_SUBMISSION_FAILURE";

export const CREATE_POSTS_REQUEST = "CREATE_POSTS_REQUEST";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";
export const CREATE_POSTS_FAILURE = "CREATE_POSTS_FAILURE";

export const CREATE_ASSIGNMENT_REQUEST = "CREATE_ASSIGNMENT_REQUEST";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const CREATE_ASSIGNMENT_FAILURE = "CREATE_ASSIGNMENT_FAILURE";

export const SUBMIT_ASSIGNMENT_REQUEST = "SUBMIT_ASSIGNMENT_REQUEST";
export const SUBMIT_ASSIGNMENT_SUCCESS = "SUBMIT_ASSIGNMENT_SUCCESS";
export const SUBMIT_ASSIGNMENT_FAILURE = "SUBMIT_ASSIGNMENT_FAILURE";

export const UNSUBMIT_ASSIGNMENT_REQUEST = "UNSUBMIT_ASSIGNMENT_REQUEST";
export const UNSUBMIT_ASSIGNMENT_SUCCESS = "UNSUBMIT_ASSIGNMENT_SUCCESS";
export const UNSUBMIT_ASSIGNMENT_FAILURE = "UNSUBMIT_ASSIGNMENT_FAILURE";

export const UPDATE_GRADE_REQUEST = "UPDATE_GRADE_REQUEST";
export const UPDATE_GRADE_SUCCESS = "UPDATE_GRADE_SUCCESS";
export const UPDATE_GRADE_FAILURE = "UPDATE_GRADE_FAILURE";