export const CREATE_EXAM_REQUEST = 'CREATE_EXAM_REQUEST';
export const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';
export const CREATE_EXAM_FAILURE = 'CREATE_EXAM_FAILURE';

export const DELETE_EXAM_REQUEST = 'DELETE_EXAM_REQUEST';
export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
export const DELETE_EXAM_FAILURE = 'DELETE_EXAM_FAILURE';

export const EDIT_EXAM_REQUEST = 'EDIT_EXAM_REQUEST';
export const EDIT_EXAM_SUCCESS = 'EDIT_EXAM_SUCCESS';
export const EDIT_EXAM_FAILURE = 'EDIT_EXAM_FAILURE';

export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';

export const EDIT_QUESTION_REQUEST = 'EDIT_QUESTION_REQUEST';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const EDIT_QUESTION_FAILURE = 'EDIT_QUESTION_FAILURE';

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE';

export const GET_EXAMS_REQUEST = 'GET_EXAMS_REQUEST';
export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS';
export const GET_EXAMS_FAILURE = 'GET_EXAMS_FAILURE';

export const GET_EXAM_REQUEST = 'GET_EXAM_REQUEST';
export const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS';
export const GET_EXAM_FAILURE = 'GET_EXAM_FAILURE';

export const GET_EXAM_REPORT_REQUEST = 'GET_EXAM_REPORT_REQUEST';
export const GET_EXAM_REPORT_SUCCESS = 'GET_EXAM_REPORT_SUCCESS';
export const GET_EXAM_REPORT_FAILURE = 'GET_EXAM_REPORT_FAILURE';

export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';